# Generated by scripts/generate_facade.py from openapi.json — do not edit.
"""The resource facade: one method per API operation. See `_base.py` for the plumbing."""

from __future__ import annotations

import builtins
from collections.abc import AsyncIterator, Iterator
from typing import Any

from . import models
from ._base import AsyncResource, Resource

from .api.audience import create_segment
from .api.audience import delete_segment
from .api.audience import list_segments
from .api.audience import refresh_segment_count
from .api.audience import update_segment
from .api.automations import add_automation_steps
from .api.automations import archive_automation
from .api.automations import backfill_missed_enrollments
from .api.automations import create_automation
from .api.automations import duplicate_automation
from .api.automations import get_automation
from .api.automations import get_automation_metrics
from .api.automations import list_automation_runs
from .api.automations import list_automations
from .api.automations import move_automation_step
from .api.automations import preflight_automation
from .api.automations import promote_ab_winner
from .api.automations import remove_automation_step
from .api.automations import set_ab_test
from .api.automations import set_automation_status
from .api.automations import sync_automation_step_props
from .api.automations import update_automation
from .api.automations import update_automation_step
from .api.contacts import delete_contact
from .api.contacts import get_contact
from .api.contacts import import_contacts
from .api.contacts import list_contact_events
from .api.contacts import list_contacts
from .api.contacts import upsert_contact
from .api.emails import cancel_email
from .api.emails import get_message
from .api.emails import list_emails
from .api.emails import reschedule_email
from .api.emails import send_email
from .api.emails import send_email_batch
from .api.events import emit_event
from .api.metrics import get_metrics
from .api.metrics import get_metrics_trends
from .api.metrics import get_queue_health
from .api.settings import get_brand
from .api.settings import get_project_settings
from .api.settings import update_brand
from .api.settings import update_project_settings
from .api.setup import create_domain
from .api.setup import create_sender
from .api.setup import delete_domain
from .api.setup import delete_sender
from .api.setup import get_connection_status
from .api.setup import get_onboarding_steps
from .api.setup import list_domains
from .api.setup import list_senders
from .api.setup import register_provider_webhook
from .api.setup import register_webhooks
from .api.setup import update_sender
from .api.setup import verify_domain
from .api.suppressions import add_suppression
from .api.suppressions import import_suppressions
from .api.suppressions import list_suppressions
from .api.suppressions import remove_suppression
from .api.templates import add_template_translation
from .api.templates import archive_template
from .api.templates import create_template
from .api.templates import get_template
from .api.templates import list_template_versions
from .api.templates import list_templates
from .api.templates import publish_template_version
from .api.templates import render_template
from .api.templates import send_template_test
from .api.templates import unpublish_template
from .api.templates import update_template
from .api.templates import update_template_meta
from .api.webhooks import create_webhook_endpoint
from .api.webhooks import delete_webhook_endpoint
from .api.webhooks import get_webhook_endpoint
from .api.webhooks import list_webhook_deliveries
from .api.webhooks import list_webhook_endpoints
from .api.webhooks import replay_webhook_delivery
from .api.webhooks import rotate_webhook_secret
from .api.webhooks import test_webhook_endpoint
from .api.webhooks import update_webhook_endpoint


class EmailsBatchResource(Resource):
    def send(self, *, emails: builtins.list[Any], idempotency_key: str | None = None) -> models.SendEmailBatchResponse202:
        """Send a batch of emails."""
        return self._call(send_email_batch, body={"emails": emails}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]


class AutomationsStepsResource(Resource):
    def add(self, *, automation: str, steps: builtins.list[Any], after_position: int | None = None, parent_step_id: str | None = None, lane_key: str | None = None) -> models.AddAutomationStepsResponse200:
        """Append automation steps."""
        return self._call(add_automation_steps, body={"automation": automation, "steps": steps, "after_position": after_position, "parent_step_id": parent_step_id, "lane_key": lane_key})  # type: ignore[no-any-return]

    def move(self, *, automation: str, position: int, direction: str | None = None, to_index: int | None = None) -> models.MoveAutomationStepResponse200:
        """Reorder a step."""
        return self._call(move_automation_step, body={"automation": automation, "position": position, "direction": direction, "to_index": to_index})  # type: ignore[no-any-return]

    def remove(self, *, automation: str, position: int) -> models.RemoveAutomationStepResponse200:
        """Remove a step."""
        return self._call(remove_automation_step, body={"automation": automation, "position": position})  # type: ignore[no-any-return]

    def sync_props(self, *, automation: str, updates: builtins.list[Any], merge: bool | None = None) -> models.SyncAutomationStepPropsResponse200:
        """Bulk-set step props."""
        return self._call(sync_automation_step_props, body={"automation": automation, "updates": updates, "merge": merge})  # type: ignore[no-any-return]

    def update(self, *, automation: str, position: int, patch: dict[str, Any]) -> models.UpdateAutomationStepResponse200:
        """Edit a step."""
        return self._call(update_automation_step, body={"automation": automation, "position": position, "patch": patch})  # type: ignore[no-any-return]


class WebhooksDeliveriesResource(Resource):
    def list(self, id: str, *, status: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListWebhookDeliveriesResponse200:
        """List deliveries."""
        return self._call(list_webhook_deliveries, id=id, status=status, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate(self, id: str, *, status: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.list(id, status=status, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def replay(self, id: str, delivery_id: str) -> models.ReplayWebhookDeliveryResponse202:
        """Replay a delivery."""
        return self._call(replay_webhook_delivery, id=id, delivery_id=delivery_id)  # type: ignore[no-any-return]


class EmailsResource(Resource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.batch = EmailsBatchResource(client)

    def cancel(self, id: str) -> models.CancelEmailResponse200:
        """Cancel an email."""
        return self._call(cancel_email, id=id)  # type: ignore[no-any-return]

    def get(self, id: str) -> models.MessageStatus:
        """Get message status."""
        return self._call(get_message, id=id)  # type: ignore[no-any-return]

    def list(self, *, status: str | None = None, to: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListEmailsResponse200:
        """List sent emails."""
        return self._call(list_emails, status=status, to=to, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate(self, *, status: str | None = None, to: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.list(status=status, to=to, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def reschedule(self, id: str, *, scheduled_at: str) -> models.RescheduleEmailResponse200:
        """Reschedule an email."""
        return self._call(reschedule_email, id=id, body={"scheduled_at": scheduled_at})  # type: ignore[no-any-return]

    def send(self, *, to: str, template: str, cc: Any | None = None, bcc: Any | None = None, props: dict[str, Any] | None = None, locale: str | None = None, from_: str | None = None, reply_to: Any | None = None, headers: dict[str, Any] | None = None, tags: builtins.list[Any] | None = None, scheduled_at: str | None = None, attachments: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.SendResult:
        """Send an email."""
        return self._call(send_email, body={"to": to, "template": template, "cc": cc, "bcc": bcc, "props": props, "locale": locale, "from": from_, "reply_to": reply_to, "headers": headers, "tags": tags, "scheduled_at": scheduled_at, "attachments": attachments}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]


class ContactsResource(Resource):
    def delete(self, id: str) -> models.DeleteContactResponse200:
        """Delete a contact."""
        return self._call(delete_contact, id=id)  # type: ignore[no-any-return]

    def events(self, id: str, *, name: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListContactEventsResponse200:
        """Contact event timeline."""
        return self._call(list_contact_events, id=id, name=name, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate_events(self, id: str, *, name: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.events(id, name=name, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def get(self, id: str) -> models.GetContactResponse200:
        """Get a contact."""
        return self._call(get_contact, id=id)  # type: ignore[no-any-return]

    def import_(self, *, contacts: builtins.list[Any], idempotency_key: str | None = None) -> models.ImportContactsResponse200:
        """Bulk import contacts."""
        return self._call(import_contacts, body={"contacts": contacts}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def list(self, *, tag: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListContactsResponse200:
        """List contacts."""
        return self._call(list_contacts, tag=tag, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate(self, *, tag: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.list(tag=tag, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def upsert(self, *, email: str, external_id: str | None = None, attributes: dict[str, Any] | None = None, tags: builtins.list[Any] | None = None) -> models.ContactResult:
        """Upsert a contact."""
        return self._call(upsert_contact, body={"email": email, "external_id": external_id, "attributes": attributes, "tags": tags})  # type: ignore[no-any-return]


class SuppressionsResource(Resource):
    def add(self, *, email: str, reason: str | None = None, note: str | None = None, idempotency_key: str | None = None) -> models.AddSuppressionResponse201:
        """Add a suppression."""
        return self._call(add_suppression, body={"email": email, "reason": reason, "note": note}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def import_(self, *, entries: builtins.list[Any], idempotency_key: str | None = None) -> models.ImportSuppressionsResponse200:
        """Bulk import suppressions."""
        return self._call(import_suppressions, body={"entries": entries}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def list(self, *, reason: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListSuppressionsResponse200:
        """List suppressions."""
        return self._call(list_suppressions, reason=reason, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate(self, *, reason: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.list(reason=reason, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def remove(self, *, email: str | None = None) -> models.RemoveSuppressionResponse200:
        """Remove a suppression."""
        return self._call(remove_suppression, email=email)  # type: ignore[no-any-return]


class EventsResource(Resource):
    def emit(self, *, name: str, email: str | None = None, external_id: str | None = None, properties: dict[str, Any] | None = None, dedupe_key: str | None = None, occurred_at: str | None = None, contact_attributes: dict[str, Any] | None = None) -> models.EmitEventResponse202:
        """Emit a contact event."""
        return self._call(emit_event, body={"name": name, "email": email, "external_id": external_id, "properties": properties, "dedupe_key": dedupe_key, "occurred_at": occurred_at, "contact_attributes": contact_attributes})  # type: ignore[no-any-return]


class TemplatesResource(Resource):
    def add_translation(self, slug: str, *, locale: str, subject: str, tsx_source: str | None = None) -> models.AddTemplateTranslationResponse201:
        """Add a translation."""
        return self._call(add_template_translation, slug=slug, body={"locale": locale, "subject": subject, "tsx_source": tsx_source})  # type: ignore[no-any-return]

    def archive(self, slug: str) -> models.ArchiveTemplateResponse200:
        """Archive a template."""
        return self._call(archive_template, slug=slug)  # type: ignore[no-any-return]

    def create(self, *, slug: str, name: str, category: str, subject: str, tsx_source: str, description: str | None = None, variables: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.CreateTemplateResponse201:
        """Create a template."""
        return self._call(create_template, body={"slug": slug, "name": name, "category": category, "subject": subject, "tsx_source": tsx_source, "description": description, "variables": variables}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def get(self, slug: str, *, version: int | None = None) -> models.GetTemplateResponse200:
        """Get a template."""
        return self._call(get_template, slug=slug, version=version)  # type: ignore[no-any-return]

    def list(self) -> models.ListTemplatesResponse200:
        """List templates."""
        return self._call(list_templates)  # type: ignore[no-any-return]

    def list_versions(self, slug: str) -> models.ListTemplateVersionsResponse200:
        """List versions."""
        return self._call(list_template_versions, slug=slug)  # type: ignore[no-any-return]

    def publish(self, slug: str, *, version: int | None = None) -> models.PublishTemplateVersionResponse200:
        """Publish a version."""
        return self._call(publish_template_version, slug=slug, body={"version": version})  # type: ignore[no-any-return]

    def render(self, slug: str, *, version: int | None = None, props: dict[str, Any] | None = None) -> models.RenderTemplateResponse200:
        """Render a template."""
        return self._call(render_template, slug=slug, body={"version": version, "props": props})  # type: ignore[no-any-return]

    def test(self, slug: str, *, to: str, version: int | None = None, props: dict[str, Any] | None = None) -> models.SendTemplateTestResponse201:
        """Send a test email."""
        return self._call(send_template_test, slug=slug, body={"to": to, "version": version, "props": props})  # type: ignore[no-any-return]

    def unpublish(self, slug: str) -> models.UnpublishTemplateResponse200:
        """Unpublish a template."""
        return self._call(unpublish_template, slug=slug)  # type: ignore[no-any-return]

    def update(self, slug: str, *, subject: str | None = None, tsx_source: str | None = None, variables: builtins.list[Any] | None = None, name: str | None = None, category: str | None = None, variant_key: str | None = None) -> models.UpdateTemplateResponse200:
        """Edit a template."""
        return self._call(update_template, slug=slug, body={"subject": subject, "tsx_source": tsx_source, "variables": variables, "name": name, "category": category, "variant_key": variant_key})  # type: ignore[no-any-return]

    def update_meta(self, slug: str, *, subject: str | None = None, preview_text: str | None = None, sender_id: Any | None = None) -> models.UpdateTemplateMetaResponse200:
        """Edit subject, preview text, or sender."""
        return self._call(update_template_meta, slug=slug, body={"subject": subject, "preview_text": preview_text, "sender_id": sender_id})  # type: ignore[no-any-return]


class AutomationsResource(Resource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.steps = AutomationsStepsResource(client)

    def archive(self, id: str) -> models.ArchiveAutomationResponse200:
        """Archive an automation."""
        return self._call(archive_automation, id=id)  # type: ignore[no-any-return]

    def backfill(self, id: str, *, since: str | None = None, dry_run: bool | None = None, max_contacts: int | None = None) -> models.BackfillMissedEnrollmentsResponse200:
        """Catch up enrollments missed while paused."""
        return self._call(backfill_missed_enrollments, id=id, body={"since": since, "dry_run": dry_run, "max_contacts": max_contacts})  # type: ignore[no-any-return]

    def create(self, *, name: str, trigger_event: str, trigger_filter: Any | None = None, priority: int | None = None, exclusive: bool | None = None, exit_events: builtins.list[Any] | None = None, exit_event: str | None = None, allow_reenrollment: bool | None = None, reenrollment_cooldown_seconds: int | None = None, steps: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.CreateAutomationResponse201:
        """Create an automation."""
        return self._call(create_automation, body={"name": name, "trigger_event": trigger_event, "trigger_filter": trigger_filter, "priority": priority, "exclusive": exclusive, "exit_events": exit_events, "exit_event": exit_event, "allow_reenrollment": allow_reenrollment, "reenrollment_cooldown_seconds": reenrollment_cooldown_seconds, "steps": steps}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def duplicate(self, id: str, *, idempotency_key: str | None = None) -> models.DuplicateAutomationResponse201:
        """Duplicate an automation."""
        return self._call(duplicate_automation, id=id, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def get(self, id: str) -> models.GetAutomationResponse200:
        """Get an automation."""
        return self._call(get_automation, id=id)  # type: ignore[no-any-return]

    def list(self) -> models.ListAutomationsResponse200:
        """List automations."""
        return self._call(list_automations)  # type: ignore[no-any-return]

    def metrics(self, id: str, *, since: str | None = None) -> models.GetAutomationMetricsResponse200:
        """Per-step funnel."""
        return self._call(get_automation_metrics, id=id, since=since)  # type: ignore[no-any-return]

    def preflight(self, id: str) -> models.PreflightAutomationResponse200:
        """Pre-launch check."""
        return self._call(preflight_automation, id=id)  # type: ignore[no-any-return]

    def promote_ab_winner(self, id: str, *, position: int) -> models.PromoteAbWinnerResponse200:
        """Promote the winning variant."""
        return self._call(promote_ab_winner, id=id, body={"position": position})  # type: ignore[no-any-return]

    def runs(self, id: str, *, status: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListAutomationRunsResponse200:
        """List enrollments."""
        return self._call(list_automation_runs, id=id, status=status, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    def iterate_runs(self, id: str, *, status: str | None = None, limit: int | None = None) -> Iterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = self.runs(id, status=status, limit=limit, cursor=cursor)
            yield from page.data
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    def set_ab_test(self, id: str, *, position: int, variants: Any) -> models.SetAbTestResponse200:
        """Set up an A/B split."""
        return self._call(set_ab_test, id=id, body={"position": position, "variants": variants})  # type: ignore[no-any-return]

    def set_status(self, id: str, *, status: str, confirm: bool | None = None) -> models.SetAutomationStatusResponse200:
        """Activate or pause."""
        return self._call(set_automation_status, id=id, body={"status": status, "confirm": confirm})  # type: ignore[no-any-return]

    def update(self, id: str, *, name: str | None = None, trigger_event: str | None = None, trigger_filter: Any | None = None, priority: int | None = None, exclusive: bool | None = None, exit_events: Any | None = None, exit_event: Any | None = None, allow_reenrollment: bool | None = None, reenrollment_cooldown_seconds: int | None = None) -> models.UpdateAutomationResponse200:
        """Edit an automation."""
        return self._call(update_automation, id=id, body={"name": name, "trigger_event": trigger_event, "trigger_filter": trigger_filter, "priority": priority, "exclusive": exclusive, "exit_events": exit_events, "exit_event": exit_event, "allow_reenrollment": allow_reenrollment, "reenrollment_cooldown_seconds": reenrollment_cooldown_seconds})  # type: ignore[no-any-return]


class DomainsResource(Resource):
    def create(self, *, domain: str, idempotency_key: str | None = None) -> models.CreateDomainResponse201:
        """Add a sending domain."""
        return self._call(create_domain, body={"domain": domain}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def delete(self, domain: str) -> models.DeleteDomainResponse200:
        """Delete a domain."""
        return self._call(delete_domain, domain=domain)  # type: ignore[no-any-return]

    def list(self) -> models.ListDomainsResponse200:
        """List domains."""
        return self._call(list_domains)  # type: ignore[no-any-return]

    def verify(self, domain: str) -> models.VerifyDomainResponse200:
        """Verify a domain."""
        return self._call(verify_domain, domain=domain)  # type: ignore[no-any-return]


class SendersResource(Resource):
    def create(self, *, from_name: str, from_email: str, reply_to: Any | None = None, make_default: bool | None = None, idempotency_key: str | None = None) -> models.CreateSenderResponse201:
        """Create a sender."""
        return self._call(create_sender, body={"from_name": from_name, "from_email": from_email, "reply_to": reply_to, "make_default": make_default}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def delete(self, id: str) -> models.DeleteSenderResponse200:
        """Delete a sender."""
        return self._call(delete_sender, id=id)  # type: ignore[no-any-return]

    def list(self) -> models.ListSendersResponse200:
        """List senders."""
        return self._call(list_senders)  # type: ignore[no-any-return]

    def update(self, id: str, *, from_name: str | None = None, reply_to: Any | None = None, is_default: bool | None = None) -> models.UpdateSenderResponse200:
        """Edit a sender."""
        return self._call(update_sender, id=id, body={"from_name": from_name, "reply_to": reply_to, "is_default": is_default})  # type: ignore[no-any-return]


class SetupResource(Resource):
    def connection(self) -> models.GetConnectionStatusResponse200:
        """Can this project send?."""
        return self._call(get_connection_status)  # type: ignore[no-any-return]

    def onboarding(self) -> models.GetOnboardingStepsResponse200:
        """How far through setup is this company?."""
        return self._call(get_onboarding_steps)  # type: ignore[no-any-return]

    def register_provider_webhook(self) -> models.RegisterProviderWebhookResponse200:
        """Register provider webhooks."""
        return self._call(register_provider_webhook)  # type: ignore[no-any-return]

    def register_webhooks(self) -> models.RegisterWebhooksResponse200:
        """Register provider webhooks (deprecated) (deprecated)."""
        return self._call(register_webhooks)  # type: ignore[no-any-return]


class WebhooksResource(Resource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.deliveries = WebhooksDeliveriesResource(client)

    def create(self, *, url: str, event_types: builtins.list[Any], description: Any | None = None, idempotency_key: str | None = None) -> models.CreateWebhookEndpointResponse201:
        """Create a webhook endpoint."""
        return self._call(create_webhook_endpoint, body={"url": url, "event_types": event_types, "description": description}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def delete(self, id: str) -> models.DeleteWebhookEndpointResponse200:
        """Delete a webhook endpoint."""
        return self._call(delete_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    def get(self, id: str) -> models.GetWebhookEndpointResponse200:
        """Get a webhook endpoint."""
        return self._call(get_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    def list(self) -> models.ListWebhookEndpointsResponse200:
        """List webhook endpoints."""
        return self._call(list_webhook_endpoints)  # type: ignore[no-any-return]

    def rotate_secret(self, id: str, *, grace_minutes: int | None = None) -> models.RotateWebhookSecretResponse200:
        """Rotate the signing secret."""
        return self._call(rotate_webhook_secret, id=id, body={"grace_minutes": grace_minutes})  # type: ignore[no-any-return]

    def test(self, id: str) -> models.TestWebhookEndpointResponse202:
        """Send a test delivery."""
        return self._call(test_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    def update(self, id: str, *, url: str | None = None, event_types: builtins.list[Any] | None = None, description: Any | None = None, enabled: bool | None = None) -> models.UpdateWebhookEndpointResponse200:
        """Update a webhook endpoint."""
        return self._call(update_webhook_endpoint, id=id, body={"url": url, "event_types": event_types, "description": description, "enabled": enabled})  # type: ignore[no-any-return]


class SegmentsResource(Resource):
    def create(self, *, name: str, filter: builtins.list[Any], description: Any | None = None, idempotency_key: str | None = None) -> models.CreateSegmentResponse201:
        """Create a segment."""
        return self._call(create_segment, body={"name": name, "filter": filter, "description": description}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    def delete(self, id: str) -> models.DeleteSegmentResponse200:
        """Delete a segment."""
        return self._call(delete_segment, id=id)  # type: ignore[no-any-return]

    def list(self) -> models.ListSegmentsResponse200:
        """List segments."""
        return self._call(list_segments)  # type: ignore[no-any-return]

    def refresh_count(self, id: str) -> models.RefreshSegmentCountResponse200:
        """Recompute member count."""
        return self._call(refresh_segment_count, id=id)  # type: ignore[no-any-return]

    def update(self, id: str, *, name: str | None = None, description: Any | None = None, filter: builtins.list[Any] | None = None) -> models.UpdateSegmentResponse200:
        """Edit a segment."""
        return self._call(update_segment, id=id, body={"name": name, "description": description, "filter": filter})  # type: ignore[no-any-return]


class MetricsResource(Resource):
    def get(self, *, since: str | None = None, until: str | None = None) -> models.GetMetricsResponse200:
        """Send funnel."""
        return self._call(get_metrics, since=since, until=until)  # type: ignore[no-any-return]

    def queue_health(self) -> models.GetQueueHealthResponse200:
        """Worker queue health."""
        return self._call(get_queue_health)  # type: ignore[no-any-return]

    def trends(self, *, days: int | None = None) -> models.GetMetricsTrendsResponse200:
        """Daily series."""
        return self._call(get_metrics_trends, days=days)  # type: ignore[no-any-return]


class SettingsResource(Resource):
    def get(self) -> models.GetProjectSettingsResponse200:
        """Get sending guardrails."""
        return self._call(get_project_settings)  # type: ignore[no-any-return]

    def get_brand(self) -> models.GetBrandResponse200:
        """Get the brand kit."""
        return self._call(get_brand)  # type: ignore[no-any-return]

    def update(self, *, sends_paused: bool | None = None, daily_send_cap: int | None = None, utm: Any | None = None, default_locale: Any | None = None, confirm: bool | None = None) -> models.UpdateProjectSettingsResponse200:
        """Set the kill switch, daily cap, auto-UTM tagging, or default locale."""
        return self._call(update_project_settings, body={"sends_paused": sends_paused, "daily_send_cap": daily_send_cap, "utm": utm, "default_locale": default_locale, "confirm": confirm})  # type: ignore[no-any-return]

    def update_brand(self, *, brand: dict[str, Any]) -> models.UpdateBrandResponse200:
        """Update the brand kit or brief."""
        return self._call(update_brand, body={"brand": brand})  # type: ignore[no-any-return]


class AsyncEmailsBatchResource(AsyncResource):
    async def send(self, *, emails: builtins.list[Any], idempotency_key: str | None = None) -> models.SendEmailBatchResponse202:
        """Send a batch of emails."""
        return await self._call(send_email_batch, body={"emails": emails}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]


class AsyncAutomationsStepsResource(AsyncResource):
    async def add(self, *, automation: str, steps: builtins.list[Any], after_position: int | None = None, parent_step_id: str | None = None, lane_key: str | None = None) -> models.AddAutomationStepsResponse200:
        """Append automation steps."""
        return await self._call(add_automation_steps, body={"automation": automation, "steps": steps, "after_position": after_position, "parent_step_id": parent_step_id, "lane_key": lane_key})  # type: ignore[no-any-return]

    async def move(self, *, automation: str, position: int, direction: str | None = None, to_index: int | None = None) -> models.MoveAutomationStepResponse200:
        """Reorder a step."""
        return await self._call(move_automation_step, body={"automation": automation, "position": position, "direction": direction, "to_index": to_index})  # type: ignore[no-any-return]

    async def remove(self, *, automation: str, position: int) -> models.RemoveAutomationStepResponse200:
        """Remove a step."""
        return await self._call(remove_automation_step, body={"automation": automation, "position": position})  # type: ignore[no-any-return]

    async def sync_props(self, *, automation: str, updates: builtins.list[Any], merge: bool | None = None) -> models.SyncAutomationStepPropsResponse200:
        """Bulk-set step props."""
        return await self._call(sync_automation_step_props, body={"automation": automation, "updates": updates, "merge": merge})  # type: ignore[no-any-return]

    async def update(self, *, automation: str, position: int, patch: dict[str, Any]) -> models.UpdateAutomationStepResponse200:
        """Edit a step."""
        return await self._call(update_automation_step, body={"automation": automation, "position": position, "patch": patch})  # type: ignore[no-any-return]


class AsyncWebhooksDeliveriesResource(AsyncResource):
    async def list(self, id: str, *, status: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListWebhookDeliveriesResponse200:
        """List deliveries."""
        return await self._call(list_webhook_deliveries, id=id, status=status, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate(self, id: str, *, status: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.list(id, status=status, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def replay(self, id: str, delivery_id: str) -> models.ReplayWebhookDeliveryResponse202:
        """Replay a delivery."""
        return await self._call(replay_webhook_delivery, id=id, delivery_id=delivery_id)  # type: ignore[no-any-return]


class AsyncEmailsResource(AsyncResource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.batch = AsyncEmailsBatchResource(client)

    async def cancel(self, id: str) -> models.CancelEmailResponse200:
        """Cancel an email."""
        return await self._call(cancel_email, id=id)  # type: ignore[no-any-return]

    async def get(self, id: str) -> models.MessageStatus:
        """Get message status."""
        return await self._call(get_message, id=id)  # type: ignore[no-any-return]

    async def list(self, *, status: str | None = None, to: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListEmailsResponse200:
        """List sent emails."""
        return await self._call(list_emails, status=status, to=to, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate(self, *, status: str | None = None, to: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.list(status=status, to=to, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def reschedule(self, id: str, *, scheduled_at: str) -> models.RescheduleEmailResponse200:
        """Reschedule an email."""
        return await self._call(reschedule_email, id=id, body={"scheduled_at": scheduled_at})  # type: ignore[no-any-return]

    async def send(self, *, to: str, template: str, cc: Any | None = None, bcc: Any | None = None, props: dict[str, Any] | None = None, locale: str | None = None, from_: str | None = None, reply_to: Any | None = None, headers: dict[str, Any] | None = None, tags: builtins.list[Any] | None = None, scheduled_at: str | None = None, attachments: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.SendResult:
        """Send an email."""
        return await self._call(send_email, body={"to": to, "template": template, "cc": cc, "bcc": bcc, "props": props, "locale": locale, "from": from_, "reply_to": reply_to, "headers": headers, "tags": tags, "scheduled_at": scheduled_at, "attachments": attachments}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]


class AsyncContactsResource(AsyncResource):
    async def delete(self, id: str) -> models.DeleteContactResponse200:
        """Delete a contact."""
        return await self._call(delete_contact, id=id)  # type: ignore[no-any-return]

    async def events(self, id: str, *, name: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListContactEventsResponse200:
        """Contact event timeline."""
        return await self._call(list_contact_events, id=id, name=name, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate_events(self, id: str, *, name: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.events(id, name=name, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def get(self, id: str) -> models.GetContactResponse200:
        """Get a contact."""
        return await self._call(get_contact, id=id)  # type: ignore[no-any-return]

    async def import_(self, *, contacts: builtins.list[Any], idempotency_key: str | None = None) -> models.ImportContactsResponse200:
        """Bulk import contacts."""
        return await self._call(import_contacts, body={"contacts": contacts}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def list(self, *, tag: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListContactsResponse200:
        """List contacts."""
        return await self._call(list_contacts, tag=tag, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate(self, *, tag: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.list(tag=tag, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def upsert(self, *, email: str, external_id: str | None = None, attributes: dict[str, Any] | None = None, tags: builtins.list[Any] | None = None) -> models.ContactResult:
        """Upsert a contact."""
        return await self._call(upsert_contact, body={"email": email, "external_id": external_id, "attributes": attributes, "tags": tags})  # type: ignore[no-any-return]


class AsyncSuppressionsResource(AsyncResource):
    async def add(self, *, email: str, reason: str | None = None, note: str | None = None, idempotency_key: str | None = None) -> models.AddSuppressionResponse201:
        """Add a suppression."""
        return await self._call(add_suppression, body={"email": email, "reason": reason, "note": note}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def import_(self, *, entries: builtins.list[Any], idempotency_key: str | None = None) -> models.ImportSuppressionsResponse200:
        """Bulk import suppressions."""
        return await self._call(import_suppressions, body={"entries": entries}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def list(self, *, reason: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListSuppressionsResponse200:
        """List suppressions."""
        return await self._call(list_suppressions, reason=reason, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate(self, *, reason: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.list(reason=reason, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def remove(self, *, email: str | None = None) -> models.RemoveSuppressionResponse200:
        """Remove a suppression."""
        return await self._call(remove_suppression, email=email)  # type: ignore[no-any-return]


class AsyncEventsResource(AsyncResource):
    async def emit(self, *, name: str, email: str | None = None, external_id: str | None = None, properties: dict[str, Any] | None = None, dedupe_key: str | None = None, occurred_at: str | None = None, contact_attributes: dict[str, Any] | None = None) -> models.EmitEventResponse202:
        """Emit a contact event."""
        return await self._call(emit_event, body={"name": name, "email": email, "external_id": external_id, "properties": properties, "dedupe_key": dedupe_key, "occurred_at": occurred_at, "contact_attributes": contact_attributes})  # type: ignore[no-any-return]


class AsyncTemplatesResource(AsyncResource):
    async def add_translation(self, slug: str, *, locale: str, subject: str, tsx_source: str | None = None) -> models.AddTemplateTranslationResponse201:
        """Add a translation."""
        return await self._call(add_template_translation, slug=slug, body={"locale": locale, "subject": subject, "tsx_source": tsx_source})  # type: ignore[no-any-return]

    async def archive(self, slug: str) -> models.ArchiveTemplateResponse200:
        """Archive a template."""
        return await self._call(archive_template, slug=slug)  # type: ignore[no-any-return]

    async def create(self, *, slug: str, name: str, category: str, subject: str, tsx_source: str, description: str | None = None, variables: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.CreateTemplateResponse201:
        """Create a template."""
        return await self._call(create_template, body={"slug": slug, "name": name, "category": category, "subject": subject, "tsx_source": tsx_source, "description": description, "variables": variables}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def get(self, slug: str, *, version: int | None = None) -> models.GetTemplateResponse200:
        """Get a template."""
        return await self._call(get_template, slug=slug, version=version)  # type: ignore[no-any-return]

    async def list(self) -> models.ListTemplatesResponse200:
        """List templates."""
        return await self._call(list_templates)  # type: ignore[no-any-return]

    async def list_versions(self, slug: str) -> models.ListTemplateVersionsResponse200:
        """List versions."""
        return await self._call(list_template_versions, slug=slug)  # type: ignore[no-any-return]

    async def publish(self, slug: str, *, version: int | None = None) -> models.PublishTemplateVersionResponse200:
        """Publish a version."""
        return await self._call(publish_template_version, slug=slug, body={"version": version})  # type: ignore[no-any-return]

    async def render(self, slug: str, *, version: int | None = None, props: dict[str, Any] | None = None) -> models.RenderTemplateResponse200:
        """Render a template."""
        return await self._call(render_template, slug=slug, body={"version": version, "props": props})  # type: ignore[no-any-return]

    async def test(self, slug: str, *, to: str, version: int | None = None, props: dict[str, Any] | None = None) -> models.SendTemplateTestResponse201:
        """Send a test email."""
        return await self._call(send_template_test, slug=slug, body={"to": to, "version": version, "props": props})  # type: ignore[no-any-return]

    async def unpublish(self, slug: str) -> models.UnpublishTemplateResponse200:
        """Unpublish a template."""
        return await self._call(unpublish_template, slug=slug)  # type: ignore[no-any-return]

    async def update(self, slug: str, *, subject: str | None = None, tsx_source: str | None = None, variables: builtins.list[Any] | None = None, name: str | None = None, category: str | None = None, variant_key: str | None = None) -> models.UpdateTemplateResponse200:
        """Edit a template."""
        return await self._call(update_template, slug=slug, body={"subject": subject, "tsx_source": tsx_source, "variables": variables, "name": name, "category": category, "variant_key": variant_key})  # type: ignore[no-any-return]

    async def update_meta(self, slug: str, *, subject: str | None = None, preview_text: str | None = None, sender_id: Any | None = None) -> models.UpdateTemplateMetaResponse200:
        """Edit subject, preview text, or sender."""
        return await self._call(update_template_meta, slug=slug, body={"subject": subject, "preview_text": preview_text, "sender_id": sender_id})  # type: ignore[no-any-return]


class AsyncAutomationsResource(AsyncResource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.steps = AsyncAutomationsStepsResource(client)

    async def archive(self, id: str) -> models.ArchiveAutomationResponse200:
        """Archive an automation."""
        return await self._call(archive_automation, id=id)  # type: ignore[no-any-return]

    async def backfill(self, id: str, *, since: str | None = None, dry_run: bool | None = None, max_contacts: int | None = None) -> models.BackfillMissedEnrollmentsResponse200:
        """Catch up enrollments missed while paused."""
        return await self._call(backfill_missed_enrollments, id=id, body={"since": since, "dry_run": dry_run, "max_contacts": max_contacts})  # type: ignore[no-any-return]

    async def create(self, *, name: str, trigger_event: str, trigger_filter: Any | None = None, priority: int | None = None, exclusive: bool | None = None, exit_events: builtins.list[Any] | None = None, exit_event: str | None = None, allow_reenrollment: bool | None = None, reenrollment_cooldown_seconds: int | None = None, steps: builtins.list[Any] | None = None, idempotency_key: str | None = None) -> models.CreateAutomationResponse201:
        """Create an automation."""
        return await self._call(create_automation, body={"name": name, "trigger_event": trigger_event, "trigger_filter": trigger_filter, "priority": priority, "exclusive": exclusive, "exit_events": exit_events, "exit_event": exit_event, "allow_reenrollment": allow_reenrollment, "reenrollment_cooldown_seconds": reenrollment_cooldown_seconds, "steps": steps}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def duplicate(self, id: str, *, idempotency_key: str | None = None) -> models.DuplicateAutomationResponse201:
        """Duplicate an automation."""
        return await self._call(duplicate_automation, id=id, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def get(self, id: str) -> models.GetAutomationResponse200:
        """Get an automation."""
        return await self._call(get_automation, id=id)  # type: ignore[no-any-return]

    async def list(self) -> models.ListAutomationsResponse200:
        """List automations."""
        return await self._call(list_automations)  # type: ignore[no-any-return]

    async def metrics(self, id: str, *, since: str | None = None) -> models.GetAutomationMetricsResponse200:
        """Per-step funnel."""
        return await self._call(get_automation_metrics, id=id, since=since)  # type: ignore[no-any-return]

    async def preflight(self, id: str) -> models.PreflightAutomationResponse200:
        """Pre-launch check."""
        return await self._call(preflight_automation, id=id)  # type: ignore[no-any-return]

    async def promote_ab_winner(self, id: str, *, position: int) -> models.PromoteAbWinnerResponse200:
        """Promote the winning variant."""
        return await self._call(promote_ab_winner, id=id, body={"position": position})  # type: ignore[no-any-return]

    async def runs(self, id: str, *, status: str | None = None, limit: int | None = None, cursor: str | None = None) -> models.ListAutomationRunsResponse200:
        """List enrollments."""
        return await self._call(list_automation_runs, id=id, status=status, limit=limit, cursor=cursor)  # type: ignore[no-any-return]

    async def iterate_runs(self, id: str, *, status: str | None = None, limit: int | None = None) -> AsyncIterator[Any]:
        """Every row of every page, following `next_cursor`."""
        cursor: str | None = None
        while True:
            page = await self.runs(id, status=status, limit=limit, cursor=cursor)
            for row in page.data:
                yield row
            cursor = page.next_cursor if isinstance(page.next_cursor, str) else None
            if not page.has_more or not cursor:
                return

    async def set_ab_test(self, id: str, *, position: int, variants: Any) -> models.SetAbTestResponse200:
        """Set up an A/B split."""
        return await self._call(set_ab_test, id=id, body={"position": position, "variants": variants})  # type: ignore[no-any-return]

    async def set_status(self, id: str, *, status: str, confirm: bool | None = None) -> models.SetAutomationStatusResponse200:
        """Activate or pause."""
        return await self._call(set_automation_status, id=id, body={"status": status, "confirm": confirm})  # type: ignore[no-any-return]

    async def update(self, id: str, *, name: str | None = None, trigger_event: str | None = None, trigger_filter: Any | None = None, priority: int | None = None, exclusive: bool | None = None, exit_events: Any | None = None, exit_event: Any | None = None, allow_reenrollment: bool | None = None, reenrollment_cooldown_seconds: int | None = None) -> models.UpdateAutomationResponse200:
        """Edit an automation."""
        return await self._call(update_automation, id=id, body={"name": name, "trigger_event": trigger_event, "trigger_filter": trigger_filter, "priority": priority, "exclusive": exclusive, "exit_events": exit_events, "exit_event": exit_event, "allow_reenrollment": allow_reenrollment, "reenrollment_cooldown_seconds": reenrollment_cooldown_seconds})  # type: ignore[no-any-return]


class AsyncDomainsResource(AsyncResource):
    async def create(self, *, domain: str, idempotency_key: str | None = None) -> models.CreateDomainResponse201:
        """Add a sending domain."""
        return await self._call(create_domain, body={"domain": domain}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def delete(self, domain: str) -> models.DeleteDomainResponse200:
        """Delete a domain."""
        return await self._call(delete_domain, domain=domain)  # type: ignore[no-any-return]

    async def list(self) -> models.ListDomainsResponse200:
        """List domains."""
        return await self._call(list_domains)  # type: ignore[no-any-return]

    async def verify(self, domain: str) -> models.VerifyDomainResponse200:
        """Verify a domain."""
        return await self._call(verify_domain, domain=domain)  # type: ignore[no-any-return]


class AsyncSendersResource(AsyncResource):
    async def create(self, *, from_name: str, from_email: str, reply_to: Any | None = None, make_default: bool | None = None, idempotency_key: str | None = None) -> models.CreateSenderResponse201:
        """Create a sender."""
        return await self._call(create_sender, body={"from_name": from_name, "from_email": from_email, "reply_to": reply_to, "make_default": make_default}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def delete(self, id: str) -> models.DeleteSenderResponse200:
        """Delete a sender."""
        return await self._call(delete_sender, id=id)  # type: ignore[no-any-return]

    async def list(self) -> models.ListSendersResponse200:
        """List senders."""
        return await self._call(list_senders)  # type: ignore[no-any-return]

    async def update(self, id: str, *, from_name: str | None = None, reply_to: Any | None = None, is_default: bool | None = None) -> models.UpdateSenderResponse200:
        """Edit a sender."""
        return await self._call(update_sender, id=id, body={"from_name": from_name, "reply_to": reply_to, "is_default": is_default})  # type: ignore[no-any-return]


class AsyncSetupResource(AsyncResource):
    async def connection(self) -> models.GetConnectionStatusResponse200:
        """Can this project send?."""
        return await self._call(get_connection_status)  # type: ignore[no-any-return]

    async def onboarding(self) -> models.GetOnboardingStepsResponse200:
        """How far through setup is this company?."""
        return await self._call(get_onboarding_steps)  # type: ignore[no-any-return]

    async def register_provider_webhook(self) -> models.RegisterProviderWebhookResponse200:
        """Register provider webhooks."""
        return await self._call(register_provider_webhook)  # type: ignore[no-any-return]

    async def register_webhooks(self) -> models.RegisterWebhooksResponse200:
        """Register provider webhooks (deprecated) (deprecated)."""
        return await self._call(register_webhooks)  # type: ignore[no-any-return]


class AsyncWebhooksResource(AsyncResource):
    def __init__(self, client: Any) -> None:
        super().__init__(client)
        self.deliveries = AsyncWebhooksDeliveriesResource(client)

    async def create(self, *, url: str, event_types: builtins.list[Any], description: Any | None = None, idempotency_key: str | None = None) -> models.CreateWebhookEndpointResponse201:
        """Create a webhook endpoint."""
        return await self._call(create_webhook_endpoint, body={"url": url, "event_types": event_types, "description": description}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def delete(self, id: str) -> models.DeleteWebhookEndpointResponse200:
        """Delete a webhook endpoint."""
        return await self._call(delete_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    async def get(self, id: str) -> models.GetWebhookEndpointResponse200:
        """Get a webhook endpoint."""
        return await self._call(get_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    async def list(self) -> models.ListWebhookEndpointsResponse200:
        """List webhook endpoints."""
        return await self._call(list_webhook_endpoints)  # type: ignore[no-any-return]

    async def rotate_secret(self, id: str, *, grace_minutes: int | None = None) -> models.RotateWebhookSecretResponse200:
        """Rotate the signing secret."""
        return await self._call(rotate_webhook_secret, id=id, body={"grace_minutes": grace_minutes})  # type: ignore[no-any-return]

    async def test(self, id: str) -> models.TestWebhookEndpointResponse202:
        """Send a test delivery."""
        return await self._call(test_webhook_endpoint, id=id)  # type: ignore[no-any-return]

    async def update(self, id: str, *, url: str | None = None, event_types: builtins.list[Any] | None = None, description: Any | None = None, enabled: bool | None = None) -> models.UpdateWebhookEndpointResponse200:
        """Update a webhook endpoint."""
        return await self._call(update_webhook_endpoint, id=id, body={"url": url, "event_types": event_types, "description": description, "enabled": enabled})  # type: ignore[no-any-return]


class AsyncSegmentsResource(AsyncResource):
    async def create(self, *, name: str, filter: builtins.list[Any], description: Any | None = None, idempotency_key: str | None = None) -> models.CreateSegmentResponse201:
        """Create a segment."""
        return await self._call(create_segment, body={"name": name, "filter": filter, "description": description}, idempotency_key=idempotency_key)  # type: ignore[no-any-return]

    async def delete(self, id: str) -> models.DeleteSegmentResponse200:
        """Delete a segment."""
        return await self._call(delete_segment, id=id)  # type: ignore[no-any-return]

    async def list(self) -> models.ListSegmentsResponse200:
        """List segments."""
        return await self._call(list_segments)  # type: ignore[no-any-return]

    async def refresh_count(self, id: str) -> models.RefreshSegmentCountResponse200:
        """Recompute member count."""
        return await self._call(refresh_segment_count, id=id)  # type: ignore[no-any-return]

    async def update(self, id: str, *, name: str | None = None, description: Any | None = None, filter: builtins.list[Any] | None = None) -> models.UpdateSegmentResponse200:
        """Edit a segment."""
        return await self._call(update_segment, id=id, body={"name": name, "description": description, "filter": filter})  # type: ignore[no-any-return]


class AsyncMetricsResource(AsyncResource):
    async def get(self, *, since: str | None = None, until: str | None = None) -> models.GetMetricsResponse200:
        """Send funnel."""
        return await self._call(get_metrics, since=since, until=until)  # type: ignore[no-any-return]

    async def queue_health(self) -> models.GetQueueHealthResponse200:
        """Worker queue health."""
        return await self._call(get_queue_health)  # type: ignore[no-any-return]

    async def trends(self, *, days: int | None = None) -> models.GetMetricsTrendsResponse200:
        """Daily series."""
        return await self._call(get_metrics_trends, days=days)  # type: ignore[no-any-return]


class AsyncSettingsResource(AsyncResource):
    async def get(self) -> models.GetProjectSettingsResponse200:
        """Get sending guardrails."""
        return await self._call(get_project_settings)  # type: ignore[no-any-return]

    async def get_brand(self) -> models.GetBrandResponse200:
        """Get the brand kit."""
        return await self._call(get_brand)  # type: ignore[no-any-return]

    async def update(self, *, sends_paused: bool | None = None, daily_send_cap: int | None = None, utm: Any | None = None, default_locale: Any | None = None, confirm: bool | None = None) -> models.UpdateProjectSettingsResponse200:
        """Set the kill switch, daily cap, auto-UTM tagging, or default locale."""
        return await self._call(update_project_settings, body={"sends_paused": sends_paused, "daily_send_cap": daily_send_cap, "utm": utm, "default_locale": default_locale, "confirm": confirm})  # type: ignore[no-any-return]

    async def update_brand(self, *, brand: dict[str, Any]) -> models.UpdateBrandResponse200:
        """Update the brand kit or brief."""
        return await self._call(update_brand, body={"brand": brand})  # type: ignore[no-any-return]


class Resources:
    """Every top-level resource, attached to a client."""

    def __init__(self, client: Any) -> None:
        self.automations = AutomationsResource(client)
        self.contacts = ContactsResource(client)
        self.domains = DomainsResource(client)
        self.emails = EmailsResource(client)
        self.events = EventsResource(client)
        self.metrics = MetricsResource(client)
        self.segments = SegmentsResource(client)
        self.senders = SendersResource(client)
        self.settings = SettingsResource(client)
        self.setup = SetupResource(client)
        self.suppressions = SuppressionsResource(client)
        self.templates = TemplatesResource(client)
        self.webhooks = WebhooksResource(client)


class AsyncResources:
    """Every top-level resource, attached to a client."""

    def __init__(self, client: Any) -> None:
        self.automations = AsyncAutomationsResource(client)
        self.contacts = AsyncContactsResource(client)
        self.domains = AsyncDomainsResource(client)
        self.emails = AsyncEmailsResource(client)
        self.events = AsyncEventsResource(client)
        self.metrics = AsyncMetricsResource(client)
        self.segments = AsyncSegmentsResource(client)
        self.senders = AsyncSendersResource(client)
        self.settings = AsyncSettingsResource(client)
        self.setup = AsyncSetupResource(client)
        self.suppressions = AsyncSuppressionsResource(client)
        self.templates = AsyncTemplatesResource(client)
        self.webhooks = AsyncWebhooksResource(client)
