# Generated by packages/public-sync — do not edit here.
#
# Edit packages/public-sync/stage.mjs in the source repo, not this file.

"""Shared runtime helpers, generated so every SDK behaves identically."""

from __future__ import annotations

import os
from dataclasses import dataclass

DEFAULT_BASE_URL = "https://sendandretain.com"
API_KEY_PREFIX = "aem_"
API_KEY_ENV_VAR = "SENDANDRETAIN_API_KEY"
BASE_URL_ENV_VAR = "SENDANDRETAIN_BASE_URL"
BRAND_NAME = "Send & Retain"

#: One minute. There was no default at all, so a hung connection hung the caller.
DEFAULT_TIMEOUT_SECONDS = 60.0

#: Longer keys are rejected, never truncated — a truncated key collides with
#: every other key sharing its prefix.
MAX_IDEMPOTENCY_KEY_LENGTH = 256


def resolve_api_key(explicit: str | None = None) -> str:
    """Resolve and validate the API key.

    Raises on a missing or wrong-shaped key. That is the only thing this SDK
    raises for by default — API failures come back as values.
    """
    key = explicit if explicit is not None else os.environ.get(API_KEY_ENV_VAR)
    if not key:
        raise ValueError(f"No API key. Pass Client(api_key=...) or set ${API_KEY_ENV_VAR}.")
    if not key.startswith(API_KEY_PREFIX):
        raise ValueError(
            f"{BRAND_NAME} API keys start with {API_KEY_PREFIX!r}; got {key[:8]!r}…. "
            "A key from another surface (or another product) will only ever 401."
        )
    return key


def resolve_base_url(explicit: str | None = None) -> str:
    return (explicit or os.environ.get(BASE_URL_ENV_VAR) or DEFAULT_BASE_URL).rstrip("/")


def user_agent(version: str) -> str:
    """Identifies the client in our logs. Matches the other SDKs' format."""
    return f"sendandretain-python:{version}"


def idempotency_headers(key: str | None) -> dict[str, str]:
    """Idempotency-Key header, or an empty dict when no key was given."""
    if not key:
        return {}
    if len(key) > MAX_IDEMPOTENCY_KEY_LENGTH:
        raise ValueError(f"Idempotency-Key must be {MAX_IDEMPOTENCY_KEY_LENGTH} characters or fewer.")
    return {"Idempotency-Key": key}


@dataclass(frozen=True)
class RateLimit:
    """Rate-limit state, present on EVERY response — success or error.

    The limit is a best-effort backstop against runaway loops, not a quota: it
    is enforced per server instance, so the real ceiling across a scaled
    deployment is higher than the advertised number.
    """

    limit: int
    remaining: int
    policy: str | None
    retry_after_ms: int | None


def rate_limit(headers: object) -> RateLimit | None:
    """Read rate-limit headers off an httpx response's .headers mapping."""
    get = getattr(headers, "get", None)
    if get is None:
        return None
    raw = get("RateLimit-Limit")
    if raw is None:
        return None
    try:
        limit = int(raw)
    except (TypeError, ValueError):
        return None
    try:
        remaining = int(get("RateLimit-Remaining") or 0)
    except (TypeError, ValueError):
        remaining = 0
    retry_after = get("Retry-After")
    retry_ms: int | None = None
    if retry_after:
        try:
            retry_ms = int(float(retry_after) * 1000)
        except (TypeError, ValueError):
            retry_ms = None
    return RateLimit(limit, remaining, get("RateLimit-Policy"), retry_ms)


def request_id(headers: object) -> str | None:
    """The request id we stamped on this response. Quote it in support requests."""
    get = getattr(headers, "get", None)
    return get("X-Request-Id") if get else None


_SUGGESTED_ACTIONS = {
    "unauthorized": (
        f"Check the key is current and starts with {API_KEY_PREFIX!r}. "
        "Mint a new one in the dashboard if it was revoked."
    ),
    "forbidden": (
        "The key is valid but its scope is too low. The error body carries "
        "required_scope and key_scope — mint a key at that tier."
    ),
    "not_found": (
        "Check the id, and that the key can reach that project — an org-scoped key may be limited to a subset."
    ),
    "rate_limited": "Back off for retry_after_ms from rate_limit(...), then retry.",
    "conflict": "Something changed underneath this call. Re-read the resource and decide again.",
    "invalid_request": ("The message names the offending field. Nothing was changed, so it is safe to fix and resend."),
    "upstream_error": (
        "A provider we depend on failed. Safe to retry with backoff; pass an "
        "idempotency key so a retry cannot double-apply."
    ),
    "internal": "Our fault. Quote request_id(...) in a support request.",
}


def suggested_action(code: str) -> str | None:
    """What to try for a given error code, or None rather than a guess."""
    return _SUGGESTED_ACTIONS.get(code)
